# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f432b65a0f655f142d378b794ed5323f0b58ec7b1f4e6735489ce615eb70698d7ca76600ddca16592cc0369b62d6d1c865535fa1d2a54b56e0996295dfa6c8

test:
  secret_key_base: d7d9c8b94ef3e4b4ec55a79372089a76605d99a6d0c25e9fe29fbbb76d7baea5bb3bd508bb97c7e435968c599514cdeec1647a28c1957ca924db3cbf8f089536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
