# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fef7e4c533fab2d78dbd7c41e6406d6dc785df2def825213588b12828b16c3ede625c355f6728b46bcaf0ee0c2ff2585a6432929122d56e73583fea7a2c9d6f

test:
  secret_key_base: 4c577080303fb4a50779251c8f3de19863d762cd4fbd4f8e5d3ab20cd65d44da883c5cde7dc81ab7f2dc23ed9862250d96166abd64c89feaa5a9b5a95ce334e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
